when:
  event: [push, pull_request, tag, deployment, manual]

steps:
  install:
    image: node:20
    commands:
      - npm install

  lint:
    image: node:20
    commands:
      - npm run lint

  test:
    image: node:20
    commands:
      - npm run coverage

  build:
    image: node:20
    commands:
      - npm run build
    when:
      branch: main
      event: push
