when:
  event: [push, pull_request, tag, deployment, manual]

steps:
  install:
    image: bash
    commands:
      - npm install

  lint:
    image: bash
    commands:
      - npm run lint

  build:
    image: bash
    commands:
      - npm run build

  test:
    image: bash
    commands:
      - npm run coverage

  e2e:
    image: bash
    environment:
      PLAYWRIGHT_BROWSERS_PATH: 0
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    commands:
      - apk add --no-cache chromium
      - cd showcase
      - npm install
      - npx playwright install chromium
      - npm run test:e2e
