when:
  event: [push, pull_request, tag, deployment, manual]

steps:
  install:
    image: bash
    commands:
      - npm install

  lint:
    image: bash
    commands:
      - npm run lint

  build:
    image: bash
    commands:
      - npm run build

  test:
    image: bash
    commands:
      - npm run coverage

  e2e:
    image: node:22-bookworm
    commands:
      - cd showcase
      - npm install
      - npx playwright install chromium --with-deps
      - npm run test:e2e
